name: video_parser
description: CLI app/package to extract metadata from a movie or TV show name
version: 1.0.0
homepage: https://github.com/dobladov/video-parser
repository: https://github.com/dobladov/video-parser
issue_tracker: https://github.com/dobladov/video-parser/issues

executables:
  video-parser: main

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  args: ^2.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.16.8
